name: tdd_action

on: push

jobs:
  ejecutar_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - run: python test_main.py
